// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package regexp

import (
	"regexp"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRegexpChecker(t *testing.T) {
	var out string
	compiledRegexp := regexp.MustCompile(`\w+`)

	// Invalid: regexp.MustCompile usage.
	{
		assert.Regexp(t, regexp.MustCompile(`\[.*\] DEBUG \(.*TestNew.*\): message`), out)                                   // want "regexp: remove unnecessary regexp\\.MustCompile"
		assert.Regexpf(t, regexp.MustCompile(`\[.*\] DEBUG \(.*TestNew.*\): message`), out, "msg with args %d %s", 42, "42") // want "regexp: remove unnecessary regexp\\.MustCompile"
		assert.NotRegexp(t, regexp.MustCompile(`\[.*\] TRACE message`), out)                                                 // want "regexp: remove unnecessary regexp\\.MustCompile"
		assert.NotRegexpf(t, regexp.MustCompile(`\[.*\] TRACE message`), out, "msg with args %d %s", 42, "42")               // want "regexp: remove unnecessary regexp\\.MustCompile"
	}

	// Invalid: non-string, non-*regexp.Regexp first argument.
	{
		assert.Regexp(t, []byte(`\w+`), out)                                      // want "regexp: use string or \\*regexp\\.Regexp as the first argument"
		assert.Regexpf(t, []byte(`\w+`), out, "msg with args %d %s", 42, "42")    // want "regexp: use string or \\*regexp\\.Regexp as the first argument"
		assert.NotRegexp(t, []byte(`\w+`), out)                                   // want "regexp: use string or \\*regexp\\.Regexp as the first argument"
		assert.NotRegexpf(t, []byte(`\w+`), out, "msg with args %d %s", 42, "42") // want "regexp: use string or \\*regexp\\.Regexp as the first argument"
	}

	// Valid.
	{
		assert.Regexp(t, `\[.*\] DEBUG \(.*TestNew.*\): message`, out)
		assert.Regexpf(t, `\[.*\] DEBUG \(.*TestNew.*\): message`, out, "msg with args %d %s", 42, "42")
		assert.NotRegexp(t, `\[.*\] TRACE message`, out)
		assert.NotRegexpf(t, `\[.*\] TRACE message`, out, "msg with args %d %s", 42, "42")
		assert.Regexp(t, compiledRegexp, out)
		assert.Regexpf(t, compiledRegexp, out, "msg with args %d %s", 42, "42")
		assert.NotRegexp(t, compiledRegexp, out)
		assert.NotRegexpf(t, compiledRegexp, out, "msg with args %d %s", 42, "42")
	}
}
