// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package failnow

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFailNowChecker(t *testing.T) {
	// Invalid.
	{
		assert.Fail(t, "failure")                                       // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Fail(t, "failure", "msg")                                // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Fail(t, "failure", "msg with arg %d", 42)                // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Fail(t, "failure", "msg with args %d %s", 42, "42")      // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Failf(t, "failure", "msg")                               // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Failf(t, "failure", "msg with arg %d", 42)               // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.Failf(t, "failure", "msg with args %d %s", 42, "42")     // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure")                                      // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure", "msg")                               // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure", "msg with arg %d", 42)               // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure", "msg with args %d %s", 42, "42")     // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Failf(t, "failure", "msg")                              // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Failf(t, "failure", "msg with arg %d", 42)              // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Failf(t, "failure", "msg with args %d %s", 42, "42")    // want "fail-now: use t\\.Error or t\\.Errorf instead"
		assert.FailNow(t, "failure")                                    // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNow(t, "failure", "msg")                             // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNow(t, "failure", "msg with arg %d", 42)             // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNow(t, "failure", "msg with args %d %s", 42, "42")   // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNowf(t, "failure", "msg")                            // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNowf(t, "failure", "msg with arg %d", 42)            // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		assert.FailNowf(t, "failure", "msg with args %d %s", 42, "42")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure")                                   // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure", "msg")                            // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure", "msg with arg %d", 42)            // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure", "msg with args %d %s", 42, "42")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNowf(t, "failure", "msg")                           // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNowf(t, "failure", "msg with arg %d", 42)           // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNowf(t, "failure", "msg with args %d %s", 42, "42") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
	}
}
