// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package failnow

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"
)

// FailNowCheckerSuite is a suite to test suite method call fixes.
type FailNowCheckerSuite struct {
	suite.Suite
}

func TestFailNowCheckerSuite(t *testing.T) {
	suite.Run(t, new(FailNowCheckerSuite))
}

func (s *FailNowCheckerSuite) TestFixSuiteMethod() {
	// Suite method calls: fixed via s.T().Error/Fatal.
	s.Fail("failure")                      // want "fail-now: use t\\.Error or t\\.Errorf instead"
	s.Fail("failure", "extra msg")         // want "fail-now: use t\\.Error or t\\.Errorf instead"
	s.Fail("failure", "fmt %s", "arg")     // want "fail-now: use t\\.Error or t\\.Errorf instead"
	s.Failf("failure", "fmt %s", "arg")    // want "fail-now: use t\\.Error or t\\.Errorf instead"
	s.FailNow("failure")                   // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
	s.FailNow("failure", "extra msg")      // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
	s.FailNow("failure", "fmt %s", "arg")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
	s.FailNowf("failure", "fmt %s", "arg") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
}

func TestFailNowChecker(t *testing.T) {
	// Invalid.
	{
		// Fail: single arg → t.Error(failureMessage).
		assert.Fail(t, "failure")  // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure") // want "fail-now: use t\\.Error or t\\.Errorf instead"
		// Fail: two args → t.Error(msg), drop failureMessage.
		assert.Fail(t, "failure", "extra msg")  // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure", "extra msg") // want "fail-now: use t\\.Error or t\\.Errorf instead"
		// Fail: three+ args → t.Errorf(format, args...), drop failureMessage.
		assert.Fail(t, "failure", "fmt %s", "arg")  // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Fail(t, "failure", "fmt %s", "arg") // want "fail-now: use t\\.Error or t\\.Errorf instead"
		// Failf: drop failureMessage, keep format + args.
		assert.Failf(t, "failure", "fmt %s", "arg")  // want "fail-now: use t\\.Error or t\\.Errorf instead"
		require.Failf(t, "failure", "fmt %s", "arg") // want "fail-now: use t\\.Error or t\\.Errorf instead"

		// FailNow: single arg → t.Fatal(failureMessage).
		assert.FailNow(t, "failure")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		// FailNow: two args → t.Fatal(msg), drop failureMessage.
		assert.FailNow(t, "failure", "extra msg")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure", "extra msg") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		// FailNow: three+ args → t.Fatalf(format, args...), drop failureMessage.
		assert.FailNow(t, "failure", "fmt %s", "arg")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNow(t, "failure", "fmt %s", "arg") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		// FailNowf: drop failureMessage, keep format + args.
		assert.FailNowf(t, "failure", "fmt %s", "arg")  // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
		require.FailNowf(t, "failure", "fmt %s", "arg") // want "fail-now: use t\\.Fatal or t\\.Fatalf instead"
	}
}
