// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package errorfirst

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func resultAndErr() (int, error)                { return 0, nil }
func errAndResult() (error, int)                { return nil, 0 }
func resultOnly() int                           { return 0 }
func resultAndErrAndMore() (int, string, error) { return 0, "", nil }

func TestErrorFirstChecker(t *testing.T) {
	// Invalid: error not checked before asserting result.
	{
		res, err := resultAndErr()
		assert.NotNil(t, res) // want "error-first: assert error before making other assertions"
		_ = err
	}

	// Invalid: error discarded with blank identifier.
	{
		res, _ := resultAndErr()
		assert.NotNil(t, res) // want "error-first: error return value was discarded; assert the error before asserting the result"
	}

	// Invalid: non-canonical error assertion (assert.Equal on err) does not satisfy the requirement.
	{
		res, err := resultAndErr()
		assert.Equal(t, nil, err) // Not a canonical error assertion.
		assert.NotNil(t, res)     // want "error-first: assert error before making other assertions"
	}

	// Invalid: error in first position (not last), not checked.
	{
		err, res := errAndResult()
		assert.NotNil(t, res) // want "error-first: assert error before making other assertions"
		_ = err
	}

	// Invalid: first call checked, second call not checked.
	{
		res, err := resultAndErr()
		require.NoError(t, err)
		res2, err2 := resultAndErr()
		assert.NotNil(t, res2) // want "error-first: assert error before making other assertions"
		_ = res
		_ = err2
	}

	// Invalid: three return values (int, string, error); error not checked.
	{
		res, msg, err := resultAndErrAndMore()
		assert.NotNil(t, res)   // want "error-first: assert error before making other assertions"
		assert.NotEmpty(t, msg) // want "error-first: assert error before making other assertions"
		_ = err
	}

	// Invalid: error discarded, both result vars flagged.
	{
		res, msg, _ := resultAndErrAndMore()
		assert.NotNil(t, res)   // want "error-first: error return value was discarded; assert the error before asserting the result"
		assert.NotEmpty(t, msg) // want "error-first: error return value was discarded; assert the error before asserting the result"
	}

	// Valid: error checked first with require.NoError.
	{
		res, err := resultAndErr()
		require.NoError(t, err)
		assert.NotNil(t, res)
	}

	// Valid: error checked first with assert.NoError.
	{
		res, err := resultAndErr()
		assert.NoError(t, err)
		assert.NotNil(t, res)
	}

	// Valid: error checked first with ErrorContains.
	{
		res, err := resultAndErr()
		require.ErrorContains(t, err, "msg")
		assert.Nil(t, res)
	}

	// Valid: error checked first with ErrorIs.
	{
		res, err := resultAndErr()
		require.ErrorIs(t, err, errors.New("msg"))
		assert.Nil(t, res)
	}

	// Valid: error assertion in if condition, result asserted in if body.
	{
		res, err := resultAndErr()
		if assert.NoError(t, err) {
			assert.NotNil(t, res)
		}
	}

	// Valid: no result used — only error asserted.
	{
		_, err := resultAndErr()
		require.NoError(t, err)
	}

	// Valid: function with no error return — not tracked.
	{
		res := resultOnly()
		assert.Equal(t, 0, res)
	}

	// Valid: transitive usage — process(res) returns no error, not tracked.
	{
		res, err := resultAndErr()
		require.NoError(t, err)
		res2 := process(res)
		assert.NotNil(t, res2)
	}

	// Valid: error in first position, checked first.
	{
		err, res := errAndResult()
		require.NoError(t, err)
		assert.NotNil(t, res)
	}

	// Valid: reassignment — first err checked, second err also checked.
	{
		res, err := resultAndErr()
		require.NoError(t, err)
		res, err = resultAndErr()
		require.NoError(t, err)
		assert.NotNil(t, res)
	}
}

func process(v int) *int { return &v }
