// Code generated by testifylint/internal/testgen. DO NOT EDIT.

package errorcompare

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestErrorCompareChecker(t *testing.T) {
	var (
		errSentinel = errors.New("user not found")
		err         error
	)

	// Invalid.
	assert.Contains(t, err.Error(), "user not found")                                      // want "error-compare: use assert\\.ErrorContains"
	assert.Containsf(t, err.Error(), "user not found", "msg with args %d %s", 42, "42")    // want "error-compare: use assert\\.ErrorContainsf"
	assert.Contains(t, err.Error(), errSentinel.Error())                                   // want "error-compare: use assert\\.ErrorIs"
	assert.Containsf(t, err.Error(), errSentinel.Error(), "msg with args %d %s", 42, "42") // want "error-compare: use assert\\.ErrorIsf"
	assert.Equal(t, err.Error(), "user not found")                                         // want "error-compare: use assert\\.EqualError"
	assert.Equalf(t, err.Error(), "user not found", "msg with args %d %s", 42, "42")       // want "error-compare: use assert\\.EqualErrorf"
	assert.Equal(t, "user not found", err.Error())                                         // want "error-compare: use assert\\.EqualError"
	assert.Equalf(t, "user not found", err.Error(), "msg with args %d %s", 42, "42")       // want "error-compare: use assert\\.EqualErrorf"
	assert.Equal(t, err, errSentinel)                                                      // want "error-compare: use assert\\.ErrorIs"
	assert.Equal(t, errSentinel, err)                                                      // want "error-compare: use assert\\.ErrorIs"
	assert.NotEqual(t, err, errSentinel)                                                   // want "error-compare: use assert\\.NotErrorIs"
	assert.NotEqual(t, errSentinel, err)                                                   // want "error-compare: use assert\\.NotErrorIs"

	// Valid.
	assert.ErrorContains(t, err, "user not found")
	assert.ErrorIs(t, err, errSentinel)
	assert.NotErrorIs(t, err, errSentinel)
	assert.EqualError(t, err, "user not found")

	// Not errors.
	str1, str2 := "foo", "bar"
	assert.Equal(t, str1, str2)
	assert.NotEqual(t, str1, str2)
	assert.Contains(t, str1, str2)
}
